[package]
name = "rust_lib_commet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "cef_host"
path = "src/bin/cef_host.rs"


[dependencies]
audio_decode = { path = "../audio_decode" }
audio_dsp = { path = "../audio_dsp" }
dj_audio = { path = "../dj_audio" }
base64 = "0.22.1"
flutter_rust_bridge = "=2.11.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = "1.23.0"

[build-dependencies]
cc = "1.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)', 'cfg(roscord_cef_bridge)'] }
